### ISSUE TITLE
Dynamic creation of bots

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-bot#16]
# Description
It needs to create the bots dynamically with its configuration data saved on the database.

# Tasks
- [x] Create the GraphQL mutation to insert bot configurations (will be executed manually, for now)
- [x] Create the GraphQL query to retrieve bots configuration data
- [x] Use express server configuration
- [x] Add process to authenticate the server to use the GraphQL with authenticated requests
- [x] Iterate through the list of bots configuration data an create the bot using its respective data
- [x] Provide a postback endpoint for each of bot to connect to it with via fb's webhook
- [x] Refactor into **factory pattern**
