### ISSUE TITLE
Feature login

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-bot#18]
# Description
It needs to add the feature that provides the possibility to user to log into bot's server using BONDE's authentication system.

# Tasks
- [x] Create the login route
- [x] Draw the login page layout
- [x] Add authentication step to login page (validations, redirects)
- [x] Add express-session
- [x] Add middleware to handle the user session
