### ISSUE TITLE
Pressure

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-bot#22]
# Description
É necessário que seja feita pressão através das interações do bot do messenger.

# Tasks
- [x] Atualizar script v1
- [x] Identificar qual foi a última pergunta do bot pra validar a resposta do usuário
- [x] Fazer pressão usando API em rails
- [x] Fazer fetch das configurações da widget usando API
- [x] Texto do email de pressão dinâmico, conforme configuração da widget no BONDE
- [x] Compartilhar na timeline do facebook

**Comment by gabrielrtakeda** [comment]
Rebase 👇
