### ISSUE TITLE
Save bot mass message campaign

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-bot#69]
# Related external repository issues
- Bot mass message campaign nossas/bonde-client#885
- Save bot mass message campaign nossas/bonde-server#381

# Description
É necessário que seja salva a campanha de envio de mensagem em massa para os usuários que interagiram com o bot, como forma de manter o histórico.

# Tasks
**Geração de histórico de campanhas**
- [x] Implementar integração com a função do GraphQL para salvar um novo registro da campanha
- [x] Alterar `enqueue-mass-message` middleware para usar [`get_facebook_activists_strategy`](https://github.com/nossas/bonde-server/pull/394)
- [x] Salvar log de erro no objeto salvo no redis com [`bull`](https://github.com/OptimalBits/bull)
- [x] Utilizar GraphQL query para fazer fetch dos ativistas da campanha no enfileiramento
- [x] Fazer com que worker de processamento da fila atualize o status de envio da mensagem

**Despoluição do Redis**
- [x] Remover job da fila de processamento após status `completed` ou `failed` (log salvos no db)
